# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Wx-Mozilla
version:      0.04
version_from: lib/Wx/Mozilla.pm
installdirs:  site
requires:
    Wx:                            0.19

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
